config/routes.rb
Rails.application.routes.draw do
  resources :event_registers
  devise_for :admins
  resources :admins
  get 'home/index'
  resources :settings
  resources :events
  root 'home#index'
  get '/reports_all', to: 'event_registers#reports_all'
  get '/reports_event', to: 'event_registers#reports_event'
  get '/thankyou', to: 'home#thankyou'
   devise_scope :admins do
     get "admins/new" => "devise/sessions#new"
    
     
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :user_temp, path: "user_temp"
      resources :registrar_evento, path: "registrar_evento"
      resources :get_eventos, path: "get_eventos"
      resources :create_admin, path: "create_admin"
    end
  end
end

app/views/admins/_form.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300|Raleway:200,900|Over+the+Rainbow' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width, user-scalable=no">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.3.1/velocity.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
<script>
    $('.hamb-wrap').on('click', function(){
      $(this).parent().children('p').toggle();
      $(this).children().toggleClass('active');
      $('nav').fadeToggle(200);
    }) 
</script>
<header>
<div class="hero">
    <article class="pa3 pa5-ns">
        <h1 class="f4 bold center mw6">Menú</h1>
        <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
          <li class="ph3 pv3 bb b--light-silver"><a href="/events">Eventos</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/admins">Administradores</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/reports_event">Reportes</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/settings">Configuración</a>
          <% if admin_signed_in? %>
          <li class="ph3 pv3 bb b--light-silver">
            <%= link_to('Salir', destroy_admin_session_path, method: :delete) %>        
            </li>
          <% end %>
      </ul>
      </article>
  </div>
  
</header>
<section class="content">
  <h1>Administradores</h1>
  <div class="ph1">

    <%= link_to 'Regresar', admins_path, :class=>"f6 link dim br2 ph3 pv2 mb2 dib white bg-green" %>
    </div>

  <div class="pa2">
    <div class="overflow-auto">
  
    <%= form_for(@user) do |f| %>
        <!--   <%# if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
              <ul>
              <%# @user.errors.full_messages.each do |message| %>
                <li><%#= message %></li>
              <%# end %>
              </ul>
            </div>
          <%# end %> -->
        
        <!-- this needs to be set to a radio button -->
          <div class="field">
            <%= f.label :email %><br>
            <%= f.text_field :email %>
          </div>
          <div class="field">
            <%= f.label :password %><br>
            <%= f.password_field :password %>
          </div>
        
          <div class="actions">
            <%= f.submit "Actualizar" %>
          </div>
    <% end %>

    </div>
  </div>
</section>

app/views/admins/_form_edit.html.erb
<article class="mw6 center bg-white br3 pa3 pa4-ns mv3 ba b--black-10">
        <h1>Administradores</h1>
         <div class="tc">
 

        <%= form_tag('/') do %>
                <div class="field">
                <%= label_tag :email %><br>
                <%= text_field_tag :email , nil ,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
                </div>
                <div class="field">
                <%= label_tag :password %><br>
                <%= password_field_tag :password ,nil ,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
            </div>
            <div><a href="javascript:postData('/api/v1/create_admin')" class="f6 grow no-underline br-pill ph3 pv2 mb2 dib white bg-dark-green" >Crear</a></div>
        <% end %>

         </div>
        </article>
        



<script>
function postData(url = ``) {
  // Default options are marked with *
   var email = $('#email').val()
   var password = $('#password').val()
   data = {email: email,password: password}
    return fetch(url, {
        method: "POST", // *GET, POST, PUT, DELETE, etc.
        mode: "cors", // no-cors, cors, *same-origin
        cache: "no-cache", // *default, no-cache, reload, force-cache, only-if-cached
        credentials: "same-origin", // include, *same-origin, omit
        headers: {
            "Content-Type": "application/json",
            // "Content-Type": "application/x-www-form-urlencoded",
        },
        redirect: "follow", // manual, *follow, error
        referrer: "no-referrer", // no-referrer, *client
        body: JSON.stringify(data), // body data type must match "Content-Type" header
       
    })
    .then(response => response.json(),window.location.href = "/admins"); // parses JSON response into native Javascript objects 
    
}
</script>

app/views/admins/edit.html.erb
<%= render 'form' %>

app/views/admins/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300|Raleway:200,900|Over+the+Rainbow' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width, user-scalable=no">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.3.1/velocity.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
<script>
    $('.hamb-wrap').on('click', function(){
      $(this).parent().children('p').toggle();
      $(this).children().toggleClass('active');
      $('nav').fadeToggle(200);
    }) 
</script>
<header>
<div class="hero">
    <article class="pa3 pa5-ns">
        <h1 class="f4 bold center mw6">Menú</h1>
        <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
          <li class="ph3 pv3 bb b--light-silver"><a href="/events">Eventos</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/admins">Administradores</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/reports_event">Reportes</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/settings">Configuración</a>
          <% if admin_signed_in? %>
          <li class="ph3 pv3 bb b--light-silver">
            <%= link_to('Salir', destroy_admin_session_path, method: :delete) %>        
            </li>
          <% end %>
      </ul>
      </article>
  </div>
  
</header>
<section class="content">
  <h1>Administradores</h1>
  <div class="ph1">
    <%= link_to 'Nuevo Administrador', new_admin_path, :class=>"f6 link dim br2 ph3 pv2 mb2 dib white bg-green" %>
  </div>

  <div class="pa2">
    <div class="overflow-auto">
  
      <table class="f6 w-100 mw8 center">
        <thead>
            <tr>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white" >Email</th>
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @users.each do |user| %>
            <tr>
                <td><%= user.email %></td>
            
                <td><%= link_to 'Detalles', user %></td>
                <td><%#= link_to 'Edit', edit_user_path(user) %></td>
                <td><%#= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
    </div>
  </div>
</section>

app/views/admins/new.html.erb
<%= render 'form_edit' %>

app/views/admins/show.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300|Raleway:200,900|Over+the+Rainbow' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width, user-scalable=no">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.3.1/velocity.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
<script>
    $('.hamb-wrap').on('click', function(){
      $(this).parent().children('p').toggle();
      $(this).children().toggleClass('active');
      $('nav').fadeToggle(200);
    }) 
</script>
<header>
<div class="hero">
    <article class="pa3 pa5-ns">
        <h1 class="f4 bold center mw6">Menú</h1>
        <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
          <li class="ph3 pv3 bb b--light-silver"><a href="/events">Eventos</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/admins">Administradores</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/reports_event">Reportes</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/settings">Configuración</a>
          <% if admin_signed_in? %>
          <li class="ph3 pv3 bb b--light-silver">
            <%= link_to('Salir', destroy_admin_session_path, method: :delete) %>        
            </li>
          <% end %>
      </ul>
      </article>
  </div>
  
</header>
<section class="content">
  <h1>Administradores</h1>
  <div class="ph1">
    <%= link_to 'Editar', edit_admin_path(@user), :class=>"f6 link dim br2 ph3 pv2 mb2 dib white bg-green" %>
  </div>

  <div class="pa2">
    <div class="overflow-auto">
  
    <strong>Email:</strong>
    <%= @user.email %>
    </div>
  </div>
</section>