config/routes.rb
Rails.application.routes.draw do
  resources :event_registers
  devise_for :admins
  resources :admins
  get 'home/index'
  resources :settings
  resources :events
  root 'home#index'
  get '/reports_all', to: 'event_registers#reports_all'
  get '/reports_event', to: 'event_registers#reports_event'
  get '/thankyou', to: 'home#thankyou'
   devise_scope :admins do
     get "admins/new" => "devise/sessions#new"
    
     
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :user_temp, path: "user_temp"
      resources :registrar_evento, path: "registrar_evento"
      resources :get_eventos, path: "get_eventos"
      resources :create_admin, path: "create_admin"
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
    require 'csv'
    paginates_per 10
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  require 'csv'
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end


  

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to "/events", notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to "/events", notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :message, :urlTolink, :active, :position, :userID, :headOne, :bodyOne, :headTwo, :bodyTwo, :boton_texto)
    end
end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_form.html.erb
<article class="mw6 center bg-white br3 pa3 pa4-ns mv3 ba b--black-10">
<h1>Eventos</h1>
 <div class="tc">
 <%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <p> Nombre del evento </p>
    <%= form.text_field :name ,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
  </div>

  <div class="field">
  <p> Descripción del evento </p>
    <%= form.text_field :description ,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
  </div>

  <div class="field">
    <p> Mensaje </p>
    <%= form.text_field :message,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
  </div>

  <div class="field">
  <p> Url de redireccionamiento </p>
    <%= form.text_field :urlTolink,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
  </div>
  <div class="field">
  <p> Texto de botón de redireccionamiento </p>
    <%= form.text_field :boton_texto,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
  </div>

  <div class="field">
   <p> Estatus del evento </p>
   
    <select class="input-reset ba b--black-20 pa2 mb2 db w-100" name="event[active]">
    <option value="">Please select</option>
    <option value="1" selected="selected">Activo</option>
    <option value="0">No activo</option>
   
  </select>
  </div>

  <div class="field">
  <p> Posición del evento </p>
    <%= form.text_field :position,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
  </div>

  <div class="field">
  <p> Código Head Página Eventos </p>
    <%= form.text_field :headOne,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
  </div>
  <div class="field">
  <p> Código Body Página Eventos </p>
    <%= form.text_field :bodyOne,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100" %>
  </div>
  <div class="field">
    <%= form.hidden_field :userID,:value => current_admin.id %>
  </div>
  <div class="actions">
    <%= form.submit "Guardar" , :class=>"f6 grow no-underline br-pill ph3 pv2 mb2 dib white bg-dark-green" %>
    <a href="/events" style="color: white" class="f6 grow no-underline br-pill ph3 pv2 mb2 dib white bg-dark-red">Cancelar</a>
  </div>
<% end %>
 </div>
</article>

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300|Raleway:200,900|Over+the+Rainbow' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width, user-scalable=no">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.3.1/velocity.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
<script>
    $('.hamb-wrap').on('click', function(){
      $(this).parent().children('p').toggle();
      $(this).children().toggleClass('active');
      $('nav').fadeToggle(200);
    }) 
</script>
<header>
<div class="hero">
    <article class="pa3 pa5-ns">
        <h1 class="f4 bold center mw6">Menú</h1>
        <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
          <li class="ph3 pv3 bb b--light-silver"><a href="/events">Eventos</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/admins">Administradores</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/reports_event">Reportes</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/settings">Configuración</a>
          <% if admin_signed_in? %>
          <li class="ph3 pv3 bb b--light-silver">
            <%= link_to('Salir', destroy_admin_session_path, method: :delete) %>        
            </li>
          <% end %>
      </ul>
      </article>
  </div>
  
</header>
<section class="content">
  <h1>Eventos</h1>
  <div class="ph1">
    <%= link_to 'Nuevo Evento', new_event_path, :class=>"f6 link dim br2 ph3 pv2 mb2 dib white bg-green" %>
  </div>

  <div class="pa2">
    <div class="overflow-auto">
      <table class="f6 w-100 mw8 center">
        <thead>
          <tr>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Evento ID</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Nombre Evento</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Descripción del Evento</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Mensaje</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Url botón registrar</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Estatus</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Posición</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Pixel Código Head</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Pixel Código Body</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.id %></td>
              <td><%= event.name %></td>
              <td><%= event.description %></td>
              <td><%= event.message %></td>
              <td><%= event.urlTolink %></td>
              <td><%= event.active %></td>
              <td><%= event.position %></td>
              <td><%= event.headOne %></td>
              <td><%= event.bodyOne %></td>
              <td><%= link_to 'Editar', edit_event_path(event) %></td>
              <td><%= link_to 'Eliminar', event, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Message:</strong>
  <%= @event.message %>
</p>

<p>
  <strong>Urltolink:</strong>
  <%= @event.urlTolink %>
</p>

<p>
  <strong>Active:</strong>
  <%= @event.active %>
</p>

<p>
  <strong>Position:</strong>
  <%= @event.position %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @event.userID %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>