config/routes.rb
Rails.application.routes.draw do
  resources :event_registers
  devise_for :admins
  resources :admins
  get 'home/index'
  resources :settings
  resources :events
  root 'home#index'
  get '/reports_all', to: 'event_registers#reports_all'
  get '/reports_event', to: 'event_registers#reports_event'
  get '/thankyou', to: 'home#thankyou'
   devise_scope :admins do
     get "admins/new" => "devise/sessions#new"
    
     
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :user_temp, path: "user_temp"
      resources :registrar_evento, path: "registrar_evento"
      resources :get_eventos, path: "get_eventos"
      resources :create_admin, path: "create_admin"
    end
  end
end

app/models/event_register.rb
class EventRegister < ApplicationRecord
   

end

app/controllers/event_registers_controller.rb
class EventRegistersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_event_register, only: [:show, :edit, :update, :destroy]
 
  # GET /event_registers
  # GET /event_registers.json
  def index
    @event_registers = EventRegister.all
  end

  def reports_all
    @event_registers = EventRegister.all
  end
  def reports_event
    
    if params[:evento]
      @registers_events = EventRegister.where(:eventId => params[:evento])
     
      respond_to do |format|
        format.html
        format.xlsx
      end
    else
      @registers_events = EventRegister.all
   
      respond_to do |format|
        format.html
        format.xlsx
      end
    end
  
  end

  # GET /event_registers/1
  # GET /event_registers/1.json
  def show
  end

  # GET /event_registers/new
  def new
    @event_register = EventRegister.new
  end

  # GET /event_registers/1/edit
  def edit
  end

  # POST /event_registers
  # POST /event_registers.json
  def create
    @event_register = EventRegister.new(event_register_params)

    respond_to do |format|
      if @event_register.save
        format.html { redirect_to @event_register, notice: 'Event register was successfully created.' }
        format.json { render :show, status: :created, location: @event_register }
      else
        format.html { render :new }
        format.json { render json: @event_register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_registers/1
  # PATCH/PUT /event_registers/1.json
  def update
    respond_to do |format|
      if @event_register.update(event_register_params)
        format.html { redirect_to @event_register, notice: 'Event register was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_register }
      else
        format.html { render :edit }
        format.json { render json: @event_register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_registers/1
  # DELETE /event_registers/1.json
  def destroy
    @event_register.destroy
    respond_to do |format|
      format.html { redirect_to event_registers_url, notice: 'Event register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_register
      @event_register = EventRegister.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_register_params
      params.require(:event_register).permit(:firtsName, :lastName, :nickName, :email, :eventId)
    end
end

app/helpers/event_registers_helper.rb
module EventRegistersHelper
end

app/views/event_registers/_form.html.erb
<%= form_with(model: event_register, local: true) do |form| %>
  <% if event_register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_register.errors.count, "error") %> prohibited this event_register from being saved:</h2>

      <ul>
      <% event_register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firtsName %>
    <%= form.text_field :firtsName %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
  </div>

  <div class="field">
    <%= form.label :nickName %>
    <%= form.text_field :nickName %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :eventId %>
    <%= form.text_field :eventId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_registers/edit.html.erb
<h1>Editing Event Register</h1>

<%= render 'form', event_register: @event_register %>

<%= link_to 'Show', @event_register %> |
<%= link_to 'Back', event_registers_path %>

app/views/event_registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Registers</h1>

<table>
  <thead>
    <tr>
      <th>Firtsname</th>
      <th>Lastname</th>
      <th>Nickname</th>
      <th>Email</th>
      <th>Eventid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_registers.each do |event_register| %>
      <tr>
        <td><%= event_register.firtsName %></td>
        <td><%= event_register.lastName %></td>
        <td><%= event_register.nickName %></td>
        <td><%= event_register.email %></td>
        <td><%= event_register.eventId %></td>
        <td><%= link_to 'Show', event_register %></td>
        <td><%= link_to 'Edit', edit_event_register_path(event_register) %></td>
        <td><%= link_to 'Destroy', event_register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Register', new_event_register_path %>

app/views/event_registers/new.html.erb
<h1>New Event Register</h1>

<%= render 'form', event_register: @event_register %>

<%= link_to 'Back', event_registers_path %>

app/views/event_registers/reports_all.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300|Raleway:200,900|Over+the+Rainbow' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width, user-scalable=no">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.3.1/velocity.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
<script>
    $('.hamb-wrap').on('click', function(){
      $(this).parent().children('p').toggle();
      $(this).children().toggleClass('active');
      $('nav').fadeToggle(200);
    }) 
</script>
<header>
<div class="hero">
    <article class="pa3 pa5-ns">
        <h1 class="f4 bold center mw6">Menú</h1>
        <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
          <li class="ph3 pv3 bb b--light-silver"><a href="/events">Eventos</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/home/index">Administradores</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/reports_all">Reporte todos los usuarios registrados</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/reports_event">Reporte usuarios por evento</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/settings">Configuración</a>
          <% if admin_signed_in? %>
          <li class="ph3 pv3 bb b--light-silver">
            <%= link_to('Salir', destroy_admin_session_path, method: :delete) %>        
            </li>
          <% end %>
      </ul>
      </article>
  </div>
  
</header>
<section class="content">
  <h1>Eventos</h1>
  <div class="ph1">
    <%= link_to 'Nuevo Evento', new_event_path, :class=>"f6 link dim br2 ph3 pv2 mb2 dib white bg-green" %>
  </div>

  <div class="pa2">
    <div class="overflow-auto">
      <table class="f6 w-100 mw8 center">
        <thead>
          <tr>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Nombre</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Apellido</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Nombre Completo</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Correo</th>
            <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">ID Evento</th>
           
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
        <% @event_registers.each do |event_register| %>
          <tr>
            <td><%= event_register.firtsName %></td>
            <td><%= event_register.lastName %></td>
            <td><%= event_register.nickName %></td>
            <td><%= event_register.email %></td>
            <td><%= event_register.eventId %></td>
            
            <td><%= link_to 'Edit', edit_event_register_path(event_register) %></td>
            <td><%= link_to 'Destroy', event_register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/event_registers/reports_event.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300|Raleway:200,900|Over+the+Rainbow' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width, user-scalable=no">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.3.1/velocity.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/es.js"></script>
  
<script>
    $('.hamb-wrap').on('click', function(){
      $(this).parent().children('p').toggle();
      $(this).children().toggleClass('active');
      $('nav').fadeToggle(200);
    }) 
</script>
<header>
<div class="hero">
    <article class="pa3 pa5-ns">
        <h1 class="f4 bold center mw6">Menú</h1>
        <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
          <li class="ph3 pv3 bb b--light-silver"><a href="/events">Eventos</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/admins">Administradores</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/reports_event">Reportes</a></li>
          <li class="ph3 pv3 bb b--light-silver"><a href="/settings">Configuración</a>
          <% if admin_signed_in? %>
          <li class="ph3 pv3 bb b--light-silver">
            <%= link_to('Salir', destroy_admin_session_path, method: :delete) %>        
            </li>
          <% end %>
      </ul>
      </article>
  </div>
  
</header>
<section class="content">
  <h1>Reportes</h1>
  <div class="ph1">
  <%= link_to "Exportar a Excel", reports_event_path(format: "xlsx", :evento => params[:evento]), :class=>"f6 link dim br2 ph3 pv2 mb2 dib white bg-green" %>
  <%= link_to "Exportar todos los usuarios registrados", reports_event_path(format: "xlsx"), :class=>"f6 link dim br2 ph3 pv2 mb2 dib white bg-green" %>
  </div>
  <p>
</p>
  <%= form_tag reports_event_path, method: :get do %>
    <div class="form-group">
      <%= text_field_tag :evento, nil,:class=> "input-reset ba b--black-20 pa2 mb2 db w-100", placeholder: "Número de evento" %>
    </div>
    <%= submit_tag "Buscar", name: nil, :class=>"f6 link dim br2 ph3 pv2 mb2 dib white bg-green" %>
  <% end %>
  
  <div class="pa2">
    <div class="overflow-auto">
    <table class="f6 w-100 mw8 center">
    <thead>
      <tr>
        <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Nombre</th>
        <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Apellido</th>
        <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Nombre Completo</th>
        <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Correo</th>
        <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">ID Evento</th>
        <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">País</th>
        <th class="fw6 bb b--black-20 tl pb3 pr3 bg-white">Fecha de Creación</th>
       
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
    <% @registers_events.each do |event_register| %>
      <tr>
        <td><%= event_register.firtsName %></td>
        <td><%= event_register.lastName %></td>
        <td><%= event_register.nickName %></td>
        <td><%= event_register.email %></td>
        <td><%= event_register.eventId %></td>
        <td><%= event_register.country %></td>
        <td><%= event_register.created_at.strftime("%d/%m/%Y")%></td>
        <td><%= link_to 'Eliminar', event_register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
    </div>
  </div>
</section>

app/views/event_registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firtsname:</strong>
  <%= @event_register.firtsName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @event_register.lastName %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @event_register.nickName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @event_register.email %>
</p>

<p>
  <strong>Eventid:</strong>
  <%= @event_register.eventId %>
</p>

<%= link_to 'Edit', edit_event_register_path(@event_register) %> |
<%= link_to 'Back', event_registers_path %>